obj-y += fih_rere.o
obj-y += fih_apr.o
obj-y += fih_hwid.o
obj-y += fih_hwcfg.o
obj-y += fih_info.o
obj-y += fih_emmc.o
obj-y += fih_dram.o
obj-y += fih_e2p.o
obj-y += fih_touch.o
# SW4-HL-Display-ImplementCECTCABC-00*_20160126
obj-y += fih_lcm.o
obj-y += fih_cpu.o
obj-y += fih_rsutoken.o

obj-$(CONFIG_FIH_DEVICE_TREE_DEBUG) += dt_debug/
obj-$(CONFIG_FIH_HALL_SENSOR) += hallsensor/

obj-y += fih_camera_dev.o

obj-$(CONFIG_FIH_MFR) += fih_mfr.o
obj-y += fih_hac.o
