#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder
obj-$(CONFIG_TOUCHSCREEN_SHTPS_FTS_FT8607) += focaltech_test_ft8607.o
obj-$(CONFIG_TOUCHSCREEN_SHTPS_FTS_FT8607) += focaltech_test_config_ft8607.o
obj-$(CONFIG_TOUCHSCREEN_SHTPS_FTS_FT8607) += focaltech_test_supported_ic.o

